### ISSUE TITLE
Tokenization instead of char by char processing

### ISSUE THREAD

**Issue by m00thie** [AlexanderPanchyshyn/Yellow-Team-JSON-Project#78]
https://github.com/AlexanderPanchyshyn/Yellow-Team-JSON-Project/blob/525b899d4d59c09af977d9717ea20b1a0566372f/src/main/java/org/yellowteam/mapper/JsonPrettifier.java#L10

I understand the general idea, but again I would suggest to tokenize the input instead of processing characters one by one. It's now the most readable way and quite hard to maintain.

**Comment by hokka1do** [comment]
Just to keep it in the code as it, just to train state pattern, and in our meeting you showed us an example of already implemented beautifier in the java to json parser.
